### ISSUE TITLE
How to use this sdk to do client_credentials authorization

### ISSUE THREAD

**Issue by wjlabcwjl** [okta/okta-sdk-python#234]
How to do the process described in this page ?
https://developer.okta.com/docs/guides/implement-grant-type/clientcreds/main/

**Comment by serhiibuniak-okta** [comment]
@wjlabcwjl Could you please, specify what exactly you want to achieve with our sdk? This SDK is used to interact with Okta management API. If you need to manipulate with tokens, we have [okta-jwt-verifier](https://github.com/okta/okta-jwt-verifier-python) for token validation, for example.

**Comment by wjlabcwjl** [comment]
> @wjlabcwjl Could you please, specify what exactly you want to achieve with our sdk? This SDK is used to interact with Okta management API. If you need to manipulate with tokens, we have [okta-jwt-verifier](https://github.com/okta/okta-jwt-verifier-python) for token validation, for example.

I want to request a token with client credentials grant type flow, I'm looking for a python helper which can do the base64 encoding and make a request with basic authorization header then return me the token.

**Comment by serhiibuniak-okta** [comment]
As a python helper I can suggest write custom function, something like the following:
```py
import requests
import base64


url = f"https://{yourOktaDomain}/oauth2/default/v1/token"
auth = f'{clientId}:{clientSecret}'
base64_encoded = base64.b64encode(auth.encode('ascii')).decode('ascii')
headers = {'Accept': 'application/json',
           'Content-Type': 'application/x-www-form-urlencoded',
           'Authorization': f'Basic {base64_encoded}'}
data = 'grant_type=client_credentials&scope=customScope'

response = requests.post(url, headers=headers, data=data)
print(response.text)
```

**Comment by wjlabcwjl** [comment]
> As a python helper I can suggest write custom function, something like the following:
> 
> ```python
> import requests
> import base64
> 
> 
> url = f"https://{yourOktaDomain}/oauth2/default/v1/token"
> auth = f'{clientId}:{clientSecret}'
> base64_encoded = base64.b64encode(auth.encode('ascii')).decode('ascii')
> headers = {'Accept': 'application/json',
>            'Content-Type': 'application/x-www-form-urlencoded',
>            'Authorization': f'Basic {base64_encoded}'}
> data = 'grant_type=client_credentials&scope=customScope'
> 
> response = requests.post(url, headers=headers, data=data)
> print(response.text)
> ```
> 
> Does it work for you?

This is what I'm doing and it works, just want to avoid this little code, I thought your sdk could do this, I see this method : https://github.com/okta/okta-sdk-python/blob/master/okta/oauth.py#L30
Well, if this is not the purpose of your sdk, you can close my issue, thanks for your help.

**Comment by serhiibuniak-okta** [comment]
And yes, you can access these internals if you want:

```py
from okta.client import Client

client = Client()

access_token, error = await client._request_executor._oauth.get_access_token()
```

**Comment by serhiibuniak-okta** [comment]
Then I'm closing this issue as resolved, feel free to reopen it or create a new one if your problem exists still.

**Comment by erichulburd** [comment]
From what I see, this client only supports API tokens and PrivateKey authorizations: https://github.com/okta/okta-sdk-python/blob/46184663baccb926dc14ab964dfd9406d375de0a/okta/config/config_validator.py#L43

So to make explicit, if we want to make a request with a client credentials access token, this client does not support our use case?

Is there a good reason to not support bearer authorization?

**Comment by serhiibuniak-okta** [comment]
@erichulburd Few years ago API didn't support Bearer tokens https://devforum.okta.com/t/using-oauth2-bearer-token-to-access-okta-apis/845/9
I think, we can add support for bearer authorization. I'll add this feature to our backlog.

**Comment by serhiibuniak-okta** [comment]
@erichulburd SDK v2.2.0 has been released, now you can pass your access token using "Bearer" authorization mode

**Comment by SquireOfSoftware** [comment]
Just wanted to say, it took me a while because the link between the documentation and the api documentation, seems to not exist...

I mean I appreciate the REST endpoints...but I was hoping for some native python examples USING the SDK for various grant flows for a native python app trying to talk to a protected resource.

My use case specifically is that I am looking to protect a new API and we were hoping to use Okta to do it. The new API is a Spring Boot application, and the Java implementation is really straight forward, thanks to this little tutorial here: https://developer.okta.com/blog/2020/08/07/spring-boot-remote-vs-local-tokens

This Python app is not your traditional, its an app that will be run at scale for automation...I was hoping to see how easy it was to adopt PKCE WITHOUT rest endpoints...but after reading around, it was suggested that perhaps client credentials is the way to go.

However for the Python side, I struggled for like a few days trying to see:
1. what the THEORY of OAuth was
2. what Okta offered AND
3. how this SDK supported what Okta offered and matched up against the theory

I ended up throwing in the towel of trying to make sense of the documentation and started reading the unit tests (which I am not sure if that is good or bad, usually if I find myself digging into third party code...its probably a bad sign of something) to see what classes I could use, what are my entrypoints into the Okta ecosystem VIA the Okta SDK lib and figure out how one might hook myself up to get a single JWT...

And so, here are the fruits of my labour (for better or for worse, feel free to let me know if I did anything horrendous or heretical, I am merely fumbling my way through this library):

```
from okta.oauth import OAuth # this is my oauth client
from okta.request_executor import RequestExecutor # unsure if this is good practice, I was not clear what this class did or what it was for, but apparently its needed?
import json

with open('public_private_pair.key', 'r') as f: # here I am extracting my JWK generated from: https://mkjwk.org/ as per the Okta documentation
    public_private_key = json.loads(f.read())

config = {
    'client': { # apparently you need a config with a client attributed nested inside? Not 100% sure why you need this, but the code seems to imply this
        'orgUrl': org_url # this is your okta domain URL
        'authorizationMode': None # I do not know what this is, I could also use `PrivateKey` but I was unsure what this actually did in Python land
        'clientId': client_id # this is your client id, defined in the Okta service app (once you have created it in the okta admin page)
        'scopes': [your_custom_api_scope] # this is the scope enabled on the Okta service app, if you are spinning up a protected resource, it must match the scope provided on the Okta admin page
        'rateLimit': {} # after a lot of tinkering, it seems it does not support numbers, and it only supports a dict (was not aware of this), subbing in a blank dict seems to let the calls pass
        'privateKey': public_private_key # you could also use an x.509 certificate as well here, the code seems to support both
    }
}

request_executor = RequestExecutor(config=config, cache={}) # not sure what the cache is for, I just subbed it out with a blank dict
oauth_client = OAuth(request_executor=request_executor, config=config) # not entirely sure why you need to provide the config twice, when the config is in the request_executor object, but anyways I subbed it in again
jwt = oauth_client.get_JWT() # this is the CLIMACTIC moment that my several days of tinkering led up to, I could finally get the damned JWT JUST to forward that over to my protected API resource so that I can verify the signature of it
print(jwt) # haha all I wanted was this little JWT and it was so much pain to reverse engineer what my inputs were to get to this point
```

Please let me know, if I have done anything heretical in my set up, but this ended up working for me, and I could verify the JWT that came back out via: https://jwt.io/ and just subbed in my dummy private and public keys.

Or feel free to let me know that I am blind and forward the documentation over my way, I could not find a lot of documentation surrounding this workflow nor examples. Most of the examples seem to be about receiving a JWT and just verifying it...which is nice...but I want to generate one to have it verified.

**Comment by serhiibuniak-okta** [comment]
@SquireOfSoftware Sorry to hear that you have had a lot of pain. Hope, I can help you to make it clear.
So, first of all, this SDK is intended to work with management APIs, i.e. it is a client to make easy and consistent interaction with APIs which are described within openapi spec https://github.com/okta/okta-management-openapi-spec. Generating and validating JWTs is not a responsibility of this SDK, although you can generate a valid token as you described in the sample above, but I can suggest a bit easier code sample:
```py
import asyncio
from okta.client import Client as OktaClient

private_key = load_private_key() # here you can use your approach or anything else to get private key

config = {
    'orgUrl': 'https://<YOUR_ORG_URL>.okta.com',
    'authorizationMode': 'PrivateKey',
    'clientId': '<CLIENT_ID>',
    'scopes': ['<YOUR_CUSTOM_API_SCOPE>'],
    'privateKey': f'{private_key}'
}


async def main():
    client = OktaClient(config)
    print(client._request_executor._oauth.get_JWT()) # generate and print access token

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```
For local token validation we have another library: https://github.com/okta/okta-jwt-verifier-python, which can be installed via pip too: `pip install okta-jwt-verifier`

Let me know if it helps. Do not hesitate to ask more and thanks for using OKTA!
